### ISSUE TITLE
atlas client does not support oidc authentication

### ISSUE THREAD

**Issue by pengfei99** [verdan/pyatlasclient#4]
Hello to all contributors, nice job.

I'd like to use this client to write a little hook for my local atlas. But my atlas uses oidc token to authenticate users. 

But your atlas client only supports login password authentication. Is there any way to integrate the oidc auth in your next release?

**Comment by verdan** [comment]
@pengfei99 indeed this is something we also want for our use case. Can not promise for the next release, but this is on our roadmap for the coming months. 
If by any chance, you have spare time and can contribute, will be really helpful. 🙂

**Comment by pengfei99** [comment]
Yes, I already cloned your code and added the oidc auth support. I'm glad to share the code with you. Or I can do a pull request. Which solution do you prefer?

**Comment by verdan** [comment]
This is amazing. Thank you so much. Please open a PR, as I would be happy to have you as a contributor.
